// API Endpoint: CRUD de RFQs

import { NextRequest, NextResponse } from 'next/server'
import { RFQEngine } from '@/lib/services/rfq/RFQEngine'
import { getCurrentUser } from '@/lib/auth'

export async function POST(request: NextRequest) {
  try {
    const user = await getCurrentUser(request)
    if (!user) {
      return NextResponse.json({ error: 'No autorizado' }, { status: 401 })
    }

    // Solo admins y operators pueden crear RFQs manualmente
    if (user.role !== 'admin_naova' && user.role !== 'operator_naova') {
      return NextResponse.json({ error: 'No autorizado' }, { status: 403 })
    }

    const body = await request.json()
    const { requestId, supplierIds, autoGenerated } = body

    if (!requestId || !supplierIds || !Array.isArray(supplierIds)) {
      return NextResponse.json(
        { error: 'requestId y supplierIds son requeridos' },
        { status: 400 }
      )
    }

    // Crear RFQ automáticamente desde request
    const rfq = await RFQEngine.createRFQFromRequest(requestId, supplierIds)

    return NextResponse.json({ rfq }, { status: 201 })
  } catch (error: any) {
    console.error('Error al crear RFQ:', error)
    return NextResponse.json(
      { error: error.message || 'Error al crear RFQ' },
      { status: 500 }
    )
  }
}

export async function GET(request: NextRequest) {
  try {
    const user = await getCurrentUser(request)
    if (!user) {
      return NextResponse.json({ error: 'No autorizado' }, { status: 401 })
    }

    // TODO: Implementar listado de RFQs con filtros
    return NextResponse.json({ rfqs: [] }, { status: 200 })
  } catch (error) {
    console.error('Error al obtener RFQs:', error)
    return NextResponse.json(
      { error: 'Error al obtener RFQs' },
      { status: 500 }
    )
  }
}

