// Type definitions for RFQ module

import { z } from 'zod'

export const RFQStatusSchema = z.enum(['draft', 'sent', 'in_progress', 'closed', 'cancelled'])

export type RFQStatus = z.infer<typeof RFQStatusSchema>

export interface RFQ {
  id: string
  requestId: string
  status: RFQStatus
  title: string
  description?: string
  deadline: Date
  items: RFQItem[]
  invitedSuppliers: RFQSupplier[]
  quotes: SupplierQuote[]
  autoGenerated: boolean
  sentAt?: Date
  createdAt: Date
  updatedAt: Date
}

export interface RFQItem {
  id: string
  rfqId: string
  specItemId?: string
  name: string
  description?: string
  category: string
  quantity: number
  unit: string
  specifications?: Record<string, any>
}

export interface RFQSupplier {
  id: string
  rfqId: string
  supplierId: string
  invitedAt: Date
  viewedAt?: Date
  respondedAt?: Date
}

export interface SupplierQuote {
  id: string
  rfqId: string
  supplierId: string
  status: 'pending' | 'submitted' | 'accepted' | 'rejected' | 'expired'
  subtotal: number
  taxes: number
  shipping: number
  total: number
  validUntil: Date
  deliveryDays: number
  paymentTerms?: string
  warranty?: string
  availability?: string
  items: QuoteItem[]
  comparisonScore?: number
  notes?: string
  submittedAt: Date
  updatedAt: Date
}

export interface QuoteItem {
  id: string
  quoteId: string
  rfqItemId?: string
  specItemId?: string
  name: string
  quantity: number
  unit: string
  unitPrice: number
  subtotal: number
  brand?: string
  model?: string
  specifications?: Record<string, any>
}

